name: Auto deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  LOC_VERSION: "libloc-0.9.5"
  LOC_DL_PATH: "loc.tar.gz"
  TOR_SRC_DIR: "tor-src"
  LOC_SRC_DIR: "loc-src"
  DUMP_PATH: "dump.txt"
  EXPORT_DIR: "public"
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl build-essential -y
      
    - name: Install latest Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Clone Tor
      run: git clone https://github.com/torproject/tor.git --depth 1 $TOR_SRC_DIR
      
    - name: Download loc
      run: curl https://source.ipfire.org/releases/libloc/$LOC_VERSION.tar.gz -o $LOC_DL_PATH
      
    - name: Extract loc
      run: |
        mkdir $LOC_SRC_DIR
        tar xfv $LOC_DL_PATH -C $LOC_SRC_DIR
      
    - name: Build and Install loc
      working-directory: ${{ env.GITHUB_WORKSPACE }}/${{ env.LOC_SRC_DIR }}/${{ env.LOC_VERSION }}
      run: |
        echo $PWD
        ./autogen.sh
        ./configure CFLAGS='-g -O2' --disable-perl --without-systemd --prefix=/opt/libloc
        make
        sudo make install
        
    - name: Dump all location data
      run: |
        location update
        location dump $DUMP_PATH
        
    - name: Run Conversion Tool
      working-directory: ${{ env.GITHUB_WORKSPACE }}/${{ env.TOR_SRC_DIR }}/scripts/maint/geoip/geoip-db-tool
      run: |
        cargo build --release
        cargo run --release -- -i $GITHUB_WORKSPACE/$DUMP_PATH -4 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip -6 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip6
      
