name: Auto deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * 1,4"
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always
  EXPORT_DIR: "public"
  IMAGE_NAME: "dragonfruit/onionfruit-geoip:current"
  TOOL_IMAGE_NAME: "dragonfruit/onionfruit-geotool:current"
  COUNTRIES_IMAGE_NAME: "dragonfruitdotnet/onionfruit-country-engine:latest"
  
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:      
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Prepare Export Directory
      run: sudo cp -R $GITHUB_WORKSPACE/$EXPORT_DIR ~/$EXPORT_DIR
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl coreutils apt-transport-https ca-certificates gnupg lsb-release -y
        
    - name: Install Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update && sudo apt install docker-ce docker-ce-cli -y

    - name: Build Location Tool
      run: docker build -t $IMAGE_NAME $GITHUB_WORKSPACE/containers/location
        
    - name: Build Data Processor Tool
      run: docker build -t $TOOL_IMAGE_NAME $GITHUB_WORKSPACE/containers/tor-geoip-tool
    
    - name: Run Location Tool
      run: |
        docker run --name geoip-control -v $(realpath ~/):/app/out $IMAGE_NAME
        docker container logs geoip-control -f
        
    - name: Run Data Processor Tool
      run: |
        docker run --name geoip-tool -v $(realpath ~/):/data-in -v $(realpath ~/$EXPORT_DIR):/data-out $TOOL_IMAGE_NAME
        docker container logs geoip-tool -f
        
    - name: Run countries.json Generator
      run: |
        docker run --name countries-generator -v $(realpath ~/$EXPORT_DIR):/output $COUNTRIES_IMAGE_NAME
        docker container logs countries-generator -f
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      if: github.repository_owner == 'dragonfruitnetwork'
      with:
        branch: live
        folder: ~/${{ env.EXPORT_DIR }}
        git-config-name: "Yuna"
        git-config-email: "inbox@dragonfruit.network"
