name: Auto deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 4 * * 1,4"
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always
  EXPORT_DIR: "/public"
  IMAGE_NAME: "dragonfruit/onionfruit-geoip:current"
  TOOL_IMAGE_NAME: "dragonfruit/onionfruit-geotool:current"
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: production
      url: https://onioncdn.dragonfruit.network
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Prepare Export Directory
      run: |
        sudo cp -R $GITHUB_WORKSPACE/$EXPORT_DIR $EXPORT_DIR
        sudo chmod -R 777 $EXPORT_DIR
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl coreutils apt-transport-https ca-certificates gnupg lsb-release -y
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build Location Tool
      run: docker build -t $IMAGE_NAME $GITHUB_WORKSPACE/containers/location
        
    - name: Build Data Processor Tool
      run: docker build -t $TOOL_IMAGE_NAME $GITHUB_WORKSPACE/containers/tor-geoip-tool
    
    - name: Run Location Tool
      run: |
        docker run --name geoip-control -v $(realpath ~/):/app/out $IMAGE_NAME
        docker container logs geoip-control -f
        
    - name: Run Data Processor Tool
      run: |
        docker run --name geoip-tool -v $(realpath ~/):/data-in -v $EXPORT_DIR:/data-out $TOOL_IMAGE_NAME
        docker container logs geoip-tool -f
        
    - name: Run Database Generator
      run: |
        cd $GITHUB_WORKSPACE/generator
        dotnet build -c Release
        OUTPUT_DIR=$EXPORT_DIR dotnet run
        
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ env.EXPORT_DIR }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
