name: Auto deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  DUMP_PATH: "~/dmp/dump.txt"
  EXPORT_DIR: "public"
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl -y
        
    - name: Install latest Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./build/Dockerfile
        push: false
        tags: dragonfruit/location:latest

    - name: Clone Tor
      run: git clone https://github.com/torproject/tor.git --depth 1 $TOR_SRC_DIR
        
    - name: Dump all location data
      run: |
        location update
        location dump ~/$DUMP_PATH
        
    - name: Run Conversion Tool
      working-directory: ${{ env.TOR_SRC_DIR }}/scripts/maint/geoip/geoip-db-tool
      run: |
        cargo build --release
        cargo run --release -- -i ~/$DUMP_PATH -4 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip -6 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip6
      
