name: Auto deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  EXPORT_DIR: "public"
  IMAGE_NAME: "dragonfruit/onionfruit-geoip:current"
  TOOL_IMAGE_NAME: "dragonfruit/onionfruit-geotool:current"
  
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl coreutils apt-transport-https ca-certificates gnupg lsb-release -y
        
    - name: Install Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update && sudo apt install docker-ce docker-ce-cli -y

    - name: Build Images
      run: |
        docker build -f $GITHUB_WORKSPACE/tools/Dockerfile -t $IMAGE_NAME .
        docker build -f $GITHUB_WORKSPACE/tools/Dockerfile-tool -t $TOOL_IMAGE_NAME .
    
    - name: Run Image
      run: |
        docker run --name geoip-control -v $(realpath ~/):/app/out $IMAGE_NAME
        docker container logs geoip-control -f
        
    - name: Run Tool
      run: |
        docker run --name geoip-tool -v $(realpath ~/):/data-in -v $(realpath $GITHUB_WORKSPACE/$EXPORT_DIR):/data-out $TOOL_IMAGE_NAME
        docker container logs geoip-tool -f
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: live
        folder: ${{ env.GITHUB_WORKSPACE }}/${{ env.EXPORT_DIR }}
