name: Auto deploy

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  EXPORT_DIR: "public"
  TOR_SRC_DIR: "~/tor-src"
  IMAGE_NAME: "dragonfruit/onionfruit-geoip:current"
  
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:      
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl coreutils apt-transport-https ca-certificates gnupg lsb-release -y
      
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Install Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update && sudo apt install docker-ce docker-ce-cli -y

    - name: Build Image
      run: docker build -f $GITHUB_WORKSPACE/tools/Dockerfile -t $IMAGE_NAME .
    
    - name: Run Image
      run: |
        docker run --name geoip-control -v $(realpath ~/):/app/out $IMAGE_NAME
        docker container logs geoip-control -f

    - name: Clone Tor
      run: git clone https://github.com/torproject/tor.git --depth 1 $TOR_SRC_DIR
        
    - name: Build Tool
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --manifest-path $TOR_SRC_DIR/scripts/maint/geoip/geoip-db-tool/Cargo.toml
        
    - name: Run Tool
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release --manifest-path $TOR_SRC_DIR/scripts/maint/geoip/geoip-db-tool/Cargo.toml -- -i ~/dmp.txt -4 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip -6 $GITHUB_WORKSPACE/$EXPORT_DIR/geoip6
